# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUw4OmkQqomgoMEGCI5Bje-qtvAr45fk
"""

pip install streamlit yfinance plotly pandas

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime

# Page Configuration
st.set_page_config(page_title="Stock Market Dashboard", layout="wide")

st.title("📈 Real-Time Stock Analysis Dashboard")
st.markdown("Enter a stock ticker (e.g., AAPL, TSLA, GOOGL) to visualize performance.")

# --- Sidebar Inputs ---
st.sidebar.header("User Input Parameters")
ticker_symbol = st.sidebar.text_input("Stock Ticker", "AAPL").upper()
start_date = st.sidebar.date_input("Start Date", value=datetime(2023, 1, 1))
end_date = st.sidebar.date_input("End Date", value=datetime.now())

# --- Data Fetching ---
@st.cache_data
def load_data(ticker, start, end):
    data = yf.download(ticker, start=start, end=end)
    return data

data = load_data(ticker_symbol, start_date, end_date)

if data.empty:
    st.error("No data found for the ticker. Please check the symbol and dates.")
else:
    # --- Dashboard Layout ---
    col1, col2, col3 = st.columns(3)

    # Metrics
    last_close = data['Close'].iloc[-1].item()
    prev_close = data['Close'].iloc[-2].item()
    delta = last_close - prev_close

    col1.metric("Current Price", f"${last_close:,.2f}", f"{delta:,.2f}")
    col2.metric("52 Week High", f"${data['High'].max().item():,.2f}")
    col3.metric("52 Week Low", f"${data['Low'].min().item():,.2f}")

    # --- Charts ---
    st.subheader(f"{ticker_symbol} - Candlestick Chart")

    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=data.index,
        open=data['Open'],
        high=data['High'],
        low=data['Low'],
        close=data['Close'],
        name='Market Data'
    ))

    # Adding a Moving Average (20-day)
    data['MA20'] = data['Close'].rolling(window=20).mean()
    fig.add_trace(go.Scatter(x=data.index, y=data['MA20'], line=dict(color='orange', width=1), name='20-Day MA'))

    fig.update_layout(template="plotly_dark", xaxis_rangeslider_visible=False, height=600)
    st.plotly_chart(fig, use_container_width=True)

    # --- Data Table ---
    with st.expander("View Raw Historical Data"):
        st.write(data.sort_index(ascending=False))