# -*- coding: utf-8 -*-
"""Capstone project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_1BiRqstZ41LlA20MC-jdIaGnQC-oi-
"""

"""
Module for fetching stock market data using yfinance
"""

import yfinance as yf
import pandas as pd
import os
from pathlib import Path

def fetch_stock_data(ticker, start_date, end_date):
    """
    Fetch historical stock data for a given ticker

    Args:
        ticker (str): Stock ticker symbol (e.g., 'AAPL')
        start_date (str): Start date in format 'YYYY-MM-DD'
        end_date (str): End date in format 'YYYY-MM-DD'

    Returns:
        pd.DataFrame: Historical stock data with OHLCV
    """
    try:
        print(f"Fetching data for {ticker}...")
        data = yf.download(ticker, start=start_date, end=end_date, progress=False)
        print(f"Successfully fetched {len(data)} records for {ticker}")
        return data
    except Exception as e:
        print(f"Error fetching data for {ticker}: {str(e)}")
        return None

def fetch_multiple_stocks(tickers, start_date, end_date):
    """
    Fetch data for multiple stocks

    Args:
        tickers (list): List of stock ticker symbols
        start_date (str): Start date in format 'YYYY-MM-DD'
        end_date (str): End date in format 'YYYY-MM-DD'

    Returns:
        dict: Dictionary with ticker as key and DataFrame as value
    """
    data = {}
    for ticker in tickers:
        stock_data = fetch_stock_data(ticker, start_date, end_date)
        if stock_data is not None:
            data[ticker] = stock_data
    return data

def save_data_to_csv(data, ticker, data_dir='data'):
    """
    Save fetched data to CSV file

    Args:
        data (pd.DataFrame): Stock data to save
        ticker (str): Stock ticker symbol
        data_dir (str): Directory to save data
    """
    # Create directory if it doesn't exist
    Path(data_dir).mkdir(parents=True, exist_ok=True)

    filepath = os.path.join(data_dir, f'{ticker}_data.csv')
    data.to_csv(filepath)
    print(f"Data saved to {filepath}")

def load_data_from_csv(ticker, data_dir='data'):
    """
    Load stock data from CSV file

    Args:
        ticker (str): Stock ticker symbol
        data_dir (str): Directory containing data files

    Returns:
        pd.DataFrame: Stock data loaded from CSV
    """
    filepath = os.path.join(data_dir, f'{ticker}_data.csv')
    try:
        data = pd.read_csv(filepath, index_col='Date', parse_dates=True)
        return data
    except FileNotFoundError:
        print(f"File not found: {filepath}")
        return None

if __name__ == "__main__":
    # Example usage
    ticker = 'AAPL', 'TSLA', 'MSFT', 'GOOGL'
    start = '2025-01-01'
    end = '2026-01-01'

    data = fetch_stock_data(ticker, start, end)
    if data is not None:
        save_data_to_csv(data, ticker)
        print(data.head)