# -*- coding: utf-8 -*-
"""capstone-pr-14-ap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/sonuk713411-netizen/a70d8b8c6ff4fab11836dc46a95abd59/capstone-pr-14-ap.ipynb

Full Code
"""

import sys
!pip install streamlit yfinance pandas numpy plotly scikit-learn textblob beautifulsoup4

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
from sklearn.linear_model import LinearRegression
from textblob import TextBlob
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup

# --- 1. PAGE CONFIG & STYLING ---
st.set_page_config(page_title="Ultimate Stock Analyzer", layout="wide")
st.title("📈 AI-Powered Stock Market Dashboard")

# --- 2. SIDEBAR INPUTS ---
st.sidebar.header("Configuration")
ticker = st.sidebar.text_input("Enter Ticker (e.g., AAPL, TSLA, RELIANCE.NS)", "AAPL")
start_date = st.sidebar.date_input("Start Date", datetime.now() - timedelta(days=365))
end_date = st.sidebar.date_input("End Date", datetime.now())

# --- 3. DATA FETCHING ---
@st.cache_data
def get_data(symbol, start, end):
    df = yf.download(symbol, start=start, end=end)
    return df

df = get_data(ticker, start_date, end_date)

if df.empty:
    st.error("Data nahi mila! Kripya sahi ticker symbol dalein.")
else:
    # --- 4. CALCULATIONS (Indicators & ML) ---
    # SMA
    df['SMA_20'] = df['Close'].rolling(window=20).mean()

    # RSI
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    df['RSI'] = 100 - (100 / (1 + (gain/loss)))

    # MACD
    exp1 = df['Close'].ewm(span=12, adjust=False).mean()
    exp2 = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = exp1 - exp2
    df['Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()

    # Machine Learning (Trend Prediction)
    df_ml = df[['Close']].copy()
    df_ml['Days'] = np.arange(len(df_ml))
    model = LinearRegression().fit(df_ml[['Days']].values, df_ml['Close'].values)
    future_days = np.array([i for i in range(len(df_ml), len(df_ml) + 30)]).reshape(-1, 1)
    future_pred = model.predict(future_days)

    # --- 5. VISUALIZATION ---
    fig = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.05, row_heights=[0.5, 0.2, 0.3])

    # Main Price Chart
    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name="Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['SMA_20'], name="SMA 20", line=dict(color='orange')), row=1, col=1)

    # RSI
    fig.add_trace(go.Scatter(x=df.index, y=df['RSI'], name="RSI", line=dict(color='purple')), row=2, col=1)

    # MACD
    fig.add_trace(go.Scatter(x=df.index, y=df['MACD'], name="MACD", line=dict(color='blue')), row=3, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['Signal'], name="Signal", line=dict(color='red')), row=3, col=1)

    fig.update_layout(height=800, template="plotly_dark", showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

    # --- 6. ML PREDICTION CHART ---
    st.subheader("🤖 30-Day Future Trend Prediction")
    pred_dates = pd.date_range(df.index[-1], periods=30)
    fig_ml = go.Figure()
    fig_ml.add_trace(go.Scatter(x=df.index[-60:], y=df['Close'][-60:], name="Actual"))
    fig_ml.add_trace(go.Scatter(x=pred_dates, y=future_pred, name="Predicted", line=dict(dash='dash', color='red')))
    st.plotly_chart(fig_ml, use_container_width=True)

    # --- 7. NEWS SENTIMENT ---
    col1, col2 = st.columns([2, 1])
    with col1:
        st.subheader("📰 Latest News & Sentiment")
        try:
            url = f'https://finviz.com/quote.ashx?t={ticker}'
            req = Request(url=url, headers={'user-agent': 'my-app'})
            html = BeautifulSoup(urlopen(req), 'html')
            news_table = html.find(id='news-table')
            news_data = []
            for row in news_table.findAll('tr')[:10]: # Top 10 News
                title = row.a.get_text()
                sentiment = "Positive ✅" if TextBlob(title).sentiment.polarity > 0 else "Negative ❌" if TextBlob(title).sentiment.polarity < 0 else "Neutral ⚪"
                news_data.append([title, sentiment])
            st.table(pd.DataFrame(news_data, columns=['Headline', 'Sentiment']))
        except:
            st.write("News currently unavailable.")

    with col2:
        st.subheader("📥 Export & Info")
        st.download_button("Download Data as CSV", df.to_csv().encode('utf-8'), f"{ticker}.csv", "text/csv")
        st.info(f"Analysis for {ticker} complete. RSI is currently at {df['RSI'].iloc[-1]:.2f}")